In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:
#1 Load the Titanic dataset and inspect its number of rows and columns. Then convert the Fare column into a NumPy array and find its mean Fare.

print(df.shape)

fare = df['Fare'].to_numpy()

print(np.mean(fare))

(891, 12)
32.204207968574636

In [3]:
#2 Using Pandas, find all passengers who are female and survived, and display only their Name, Age, Pclass, and Fare.

df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1),['Name','Age','Pclass','Fare']]

                                                  Name   Age  Pclass     Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1  71.2833
2                               Heikkinen, Miss. Laina  26.0       3   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1  53.1000
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3  11.1333
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0       2  30.0708
..                                                 ...   ...     ...      ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0       2  24.0000
875                   Najib, Miss. Adele Kiamie "Jane"  15.0       3   7.2250
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1  83.1583
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0       2  26.0000
887                       Graham, Miss. Margaret Edith  19.0       1  30.0000

[233 rows x 4 columns]

In [4]:
#3 Create a NumPy array from Fare and find the indices of the 10 highest fares. Use those indices to display the corresponding passengers' Name and Fare from the DataFrame. 

fare = df['Fare'].to_numpy()

highest = np.argsort(fare)[-10:][::-1]

show = df.loc[highest,['Name','Fare']]

show

                                                Name      Fare
258                                 Ward, Miss. Anna  512.3292
679               Cardeza, Mr. Thomas Drake Martinez  512.3292
737                           Lesurer, Mr. Gustave J  512.3292
341                   Fortune, Miss. Alice Elizabeth  263.0000
438                                Fortune, Mr. Mark  263.0000
27                    Fortune, Mr. Charles Alexander  263.0000
88                        Fortune, Miss. Mabel Helen  263.0000
311                       Ryerson, Miss. Emily Borie  262.3750
742            Ryerson, Miss. Susan Parker "Suzette"  262.3750
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208

In [5]:
#4 Find the number of missing values in the Age column. Then create a NumPy Age array and replace its missing values with the overall median Age. 

age = df['Age'].to_numpy()

null = np.sum(np.isnan(age))

median = np.nanmedian(age)

print(np.where(np.isnan(age),median,age))

[22.   38.   26.   35.   35.   28.   54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.   28.   31.   28.   35.   34.   15.   28.
  8.   38.   28.   19.   28.   28.   40.   28.   28.   66.   28.   42.
 28.   21.   18.   14.   40.   27.   28.    3.   19.   28.   28.   28.
 28.   18.    7.   21.   49.   29.   65.   28.   21.   28.5   5.   11.
 22.   38.   45.    4.   28.   28.   29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.   28.   28.    0.83 30.   22.   29.   28.   28.
 17.   33.   16.   28.   23.   24.   29.   20.   46.   26.   59.   28.
 71.   23.   34.   34.   28.   28.   21.   33.   37.   28.   21.   28.
 38.   28.   47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.   28.   32.5  32.5  54.   12.   28.   24.   28.   45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.   28.   22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5  28.   51.
 16.   30.   28.   28.   44.   40.   26.   17.    1.    9.   28.   45.
 28.   28.   61.    4.    1.   21.   56.   18.   28.   50.   30.   36.
 28.   28.    9.    1.    4.   28.   28.   45.   40.   36.   32.   19.
 19.    3.   44.   58.   28.   42.   28.   24.   28.   28.   34.   45.5
 18.    2.   32.   26.   16.   40.   24.   35.   22.   30.   28.   31.
 27.   42.   32.   30.   16.   27.   51.   28.   38.   22.   19.   20.5
 18.   28.   35.   29.   59.    5.   24.   28.   44.    8.   19.   33.
 28.   28.   29.   22.   30.   44.   25.   24.   37.   54.   28.   29.
 62.   30.   41.   29.   28.   30.   35.   50.   28.    3.   52.   40.
 28.   36.   16.   25.   58.   35.   28.   25.   41.   37.   28.   63.
 45.   28.    7.   35.   65.   28.   16.   19.   28.   33.   30.   22.
 42.   22.   26.   19.   36.   24.   24.   28.   23.5   2.   28.   50.
 28.   28.   19.   28.   28.    0.92 28.   17.   30.   30.   24.   18.
 26.   28.   43.   26.   24.   54.   31.   40.   22.   27.   30.   22.
 28.   36.   61.   36.   31.   16.   28.   45.5  38.   16.   28.   28.
 29.   41.   45.   45.    2.   24.   28.   25.   36.   24.   40.   28.
  3.   42.   23.   28.   15.   25.   28.   28.   22.   38.   28.   28.
 40.   29.   45.   35.   28.   30.   60.   28.   28.   24.   25.   18.
 19.   22.    3.   28.   22.   27.   20.   19.   42.    1.   32.   35.
 28.   18.    1.   36.   28.   17.   36.   21.   28.   23.   24.   22.
 31.   46.   23.   28.   39.   26.   21.   28.   20.   34.   51.    3.
 21.   28.   28.   28.   33.   28.   44.   28.   34.   18.   30.   10.
 28.   21.   29.   28.   18.   28.   28.   19.   28.   32.   28.   28.
 42.   17.   50.   14.   21.   24.   64.   31.   45.   20.   25.   28.
 28.    4.   13.   34.    5.   52.   36.   28.   30.   49.   28.   29.
 65.   28.   50.   28.   48.   34.   47.   48.   28.   38.   28.   56.
 28.    0.75 28.   38.   33.   23.   22.   28.   34.   29.   22.    2.
  9.   28.   50.   63.   25.   28.   35.   58.   30.    9.   28.   21.
 55.   71.   21.   28.   54.   28.   25.   24.   17.   21.   28.   37.
 16.   18.   33.   28.   28.   26.   29.   28.   36.   54.   24.   47.
 34.   28.   36.   32.   30.   22.   28.   44.   28.   40.5  50.   28.
 39.   23.    2.   28.   17.   28.   30.    7.   45.   30.   28.   22.
 36.    9.   11.   32.   50.   64.   19.   28.   33.    8.   17.   27.
 28.   22.   22.   62.   48.   28.   39.   36.   28.   40.   28.   28.
 28.   24.   19.   29.   28.   32.   62.   53.   36.   28.   16.   19.
 34.   39.   28.   32.   25.   39.   54.   36.   28.   18.   47.   60.
 22.   28.   35.   52.   47.   28.   37.   36.   28.   49.   28.   49.
 24.   28.   28.   44.   35.   36.   30.   27.   22.   40.   39.   28.
 28.   28.   35.   24.   34.   26.    4.   26.   27.   42.   20.   21.
 21.   61.   57.   21.   26.   28.   80.   51.   32.   28.    9.   28.
 32.   31.   41.   28.   20.   24.    2.   28.    0.75 48.   19.   56.
 28.   23.   28.   18.   21.   28.   18.   24.   28.   32.   23.   58.
 50.   40.   47.   36.   20.   32.   25.   28.   43.   28.   40.   31.
 70.   31.   28.   18.   24.5  18.   43.   36.   28.   27.   20.   14.
 60.   25.   14.   19.   18.   15.   31.    4.   28.   25.   60.   52.
 44.   28.   49.   42.   18.   35.   18.   25.   26.   39.   45.   42.
 22.   28.   24.   28.   48.   29.   52.   19.   38.   27.   28.   33.
  6.   17.   34.   50.   27.   20.   30.   28.   25.   25.   29.   11.
 28.   23.   23.   28.5  48.   35.   28.   28.   28.   36.   21.   24.
 31.   70.   16.   30.   19.   31.    4.    6.   33.   23.   48.    0.67
 28.   18.   34.   33.   28.   41.   20.   36.   16.   51.   28.   30.5
 28.   32.   24.   48.   57.   28.   54.   18.   28.    5.   28.   43.
 13.   17.   29.   28.   25.   25.   18.    8.    1.   46.   28.   16.
 28.   28.   25.   39.   49.   31.   30.   30.   34.   31.   11.    0.42
 27.   31.   39.   18.   39.   33.   26.   39.   35.    6.   30.5  28.
 23.   31.   43.   10.   52.   27.   38.   27.    2.   28.   28.    1.
 28.   62.   15.    0.83 28.   23.   18.   39.   21.   28.   32.   28.
 20.   16.   30.   34.5  17.   42.   28.   35.   28.   28.    4.   74.
  9.   16.   44.   18.   45.   51.   24.   28.   41.   21.   48.   28.
 24.   42.   27.   31.   28.    4.   26.   47.   33.   47.   28.   15.
 20.   19.   28.   56.   25.   33.   22.   28.   25.   39.   27.   19.
 28.   26.   32.  ]

In [6]:
#5 
"""
Using Pandas, find passengers who satisfy all of these conditions: 
 Age is greater than 30  
 Fare is greater than 100  
 Passenger survived  
Display their Name, Age, Fare, and Pclass.
"""

filter = df.loc[(df['Age'] > 30) & (df['Fare'] > 100) & (df['Survived'] == 1),['Name','Age','Fare','Pclass']]

print(filter)

                                                  Name   Age      Fare  Pclass
195                               Lurette, Miss. Elise  58.0  146.5208       1
215                            Newell, Miss. Madeleine  31.0  113.2750       1
258                                   Ward, Miss. Anna  35.0  512.3292       1
268      Graham, Mrs. William Thompson (Edith Junkins)  58.0  153.4625       1
269                             Bissette, Miss. Amelia  35.0  135.6333       1
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  50.0  247.5208       1
318                           Wick, Miss. Mary Natalie  31.0  164.8667       1
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  40.0  134.5000       1
325                           Young, Miss. Marie Grice  36.0  135.6333       1
337                    Burns, Miss. Elizabeth Margaret  41.0  134.5000       1
380                              Bidois, Miss. Rosalie  42.0  227.5250       1
390                         Carter, Mr. William Ernest  36.0  120.0000       1
581  Thayer, Mrs. John Borland (Marian Longstreth M...  39.0  110.8833       1
609                          Shutes, Miss. Elizabeth W  40.0  153.4625       1
660                      Frauenthal, Dr. Henry William  50.0  133.6500       1
679                 Cardeza, Mr. Thomas Drake Martinez  36.0  512.3292       1
716                      Endres, Miss. Caroline Louise  38.0  227.5250       1
737                             Lesurer, Mr. Gustave J  35.0  512.3292       1
763          Carter, Mrs. William Ernest (Lucile Polk)  36.0  120.0000       1
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  43.0  211.3375       1
856         Wick, Mrs. George Dennick (Mary Hitchcock)  45.0  164.8667       1

In [7]:
#6 Check the data type of Fare. Convert Fare to a numeric data type if necessary, create a NumPy array from it, and find the minimum, maximum, and mean Fare.

fare = df['Fare'].to_numpy()

print(df['Fare'].dtype)

print(np.min(fare))
print(np.max(fare))
print(np.mean(fare))

float64
0.0
512.3292
32.204207968574636

In [13]:
#7 Using Pandas, select Pclass, Age, SibSp, Parch, and Fare. Replace missing Age values with the median Age, convert the selected data into a NumPy matrix, and display its shape. 

median = np.nanmedian(df['Age'])

selected = df[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']].copy()

selected['Age'] = selected['Age'].fillna(median)

matrix = selected.to_numpy()

print(matrix)
print(matrix.shape)

[[ 3.     22.      1.      0.      7.25  ]
 [ 1.     38.      1.      0.     71.2833]
 [ 3.     26.      0.      0.      7.925 ]
 ...
 [ 3.     28.      1.      2.     23.45  ]
 [ 1.     26.      0.      0.     30.    ]
 [ 3.     32.      0.      0.      7.75  ]]
(891, 5)

In [17]:
#8 Create a NumPy array from Fare. Increase fares above 200 by 5% and fares of 200 or below by 10%. Store the transformed values back into the DataFrame as a new column called AdjustedFare.

fare = df['Fare'].to_numpy()

increased = np.where(fare > 200, fare + (fare * 5) / 100, fare + (fare * 10) / 100)

df['AdjustedFare'] = increased

print(df[['Fare', 'AdjustedFare']])

        Fare  AdjustedFare
0     7.2500       7.97500
1    71.2833      78.41163
2     7.9250       8.71750
3    53.1000      58.41000
4     8.0500       8.85500
..       ...           ...
886  13.0000      14.30000
887  30.0000      33.00000
888  23.4500      25.79500
889  30.0000      33.00000
890   7.7500       8.52500

[891 rows x 2 columns]

In [23]:
#9 Create a NumPy matrix containing Pclass, Age, SibSp, Parch, and Fare. Replace missing Age values with the median Age and sort the complete matrix by Fare from highest to lowest.

pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

median = np.nanmedian(age)

age = np.where(np.isnan(age),median,age)

mat = np.column_stack((pclass,age,sibsp,parch,fare))

sort = mat[np.argsort(mat[:, 4])[::-1]]

print(sort)

[[  1.      35.       0.       0.     512.3292]
 [  1.      36.       0.       1.     512.3292]
 [  1.      35.       0.       0.     512.3292]
 ...
 [  2.      28.       0.       0.       0.    ]
 [  1.      39.       0.       0.       0.    ]
 [  1.      28.       0.       0.       0.    ]]

In [29]:
#10 Using Pandas and NumPy, create a feature matrix containing Survived, Pclass, Age, SibSp, Parch, and Fare. Handle missing Age using the median, min-max normalize Fare, and transpose the final NumPy matrix.

median = np.nanmedian(df['Age'])

selected = df[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']].copy()

selected['Age'] = selected['Age'].fillna(median)

fare_min = selected['Fare'].min()
fare_max = selected['Fare'].max()

selected['Fare'] = ((selected['Fare'] - fare_min) /(fare_max - fare_min))

matrix = selected.to_numpy()

final_matrix = matrix.T

print(final_matrix)

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [3.00000000e+00 1.00000000e+00 3.00000000e+00 ... 3.00000000e+00
  1.00000000e+00 3.00000000e+00]
 [2.20000000e+01 3.80000000e+01 2.60000000e+01 ... 2.80000000e+01
  2.60000000e+01 3.20000000e+01]
 [1.00000000e+00 1.00000000e+00 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.41510576e-02 1.39135735e-01 1.54685698e-02 ... 4.57713517e-02
  5.85561003e-02 1.51269926e-02]]