In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
#1 Using Pandas, find the average Fare for each Pclass using groupby() and agg(). 

df.groupby('Pclass')['Fare'].agg('mean')

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [19]:
#2 Using Pandas string operations, find all passengers whose Name contains "William". Display only Name, Sex, Age, and Fare.

will = df.loc[df['Name'].str.contains('William'),['Name','Sex','Age','Fare']]

will

                                               Name     Sex   Age      Fare
4                          Allen, Mr. William Henry    male  35.0    8.0500
12                   Saundercock, Mr. William Henry    male  20.0    8.0500
17                     Williams, Mr. Charles Eugene    male   NaN   13.0000
23                     Sloper, Mr. William Thompson    male  28.0   35.5000
31   Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN  146.5208
..                                              ...     ...   ...       ...
802             Carter, Master. William Thornton II    male  11.0  120.0000
810                          Alexander, Mr. William    male  26.0    7.8875
864                          Gill, Mr. John William    male  24.0   13.0000
880    Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0   26.0000
885            Rice, Mrs. William (Margaret Norton)  female  39.0   29.1250

[69 rows x 4 columns]

In [21]:
#3 
"""
Using Pandas, create a new column called FamilySize: 
FamilySize = SibSp + Parch + 1 

Then display Name, FamilySize, and Survived for the 10 passengers with the largest 
FamilySize. 
"""

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

large = df.sort_values('FamilySize', ascending=False)

large[['Name', 'FamilySize', 'Survived']].head(10)

                                   Name  FamilySize  Survived
846            Sage, Mr. Douglas Bullen          11         0
324            Sage, Mr. George John Jr          11         0
792             Sage, Miss. Stella Anna          11         0
180        Sage, Miss. Constance Gladys          11         0
159          Sage, Master. Thomas Henry          11         0
201                 Sage, Mr. Frederick          11         0
863   Sage, Miss. Dorothy Edith "Dolly"          11         0
59   Goodwin, Master. William Frederick           8         0
71           Goodwin, Miss. Lillian Amy           8         0
683         Goodwin, Mr. Charles Edward           8         0

In [23]:
#4 
"""
Using groupby() and agg(), find for each Sex: 
 average Age  
 average Fare  
 survival rate 
"""

sex = df.groupby('Sex').agg({
    'Age': 'mean',
    'Fare': 'mean',
    'Survived': 'mean'
})

sex['Survived'] = sex['Survived'] * 100

sex

              Age       Fare   Survived
Sex
female  27.915709  44.479818  74.203822
male    30.726645  25.523893  18.890815

In [30]:
#5 Convert the Fare column to a NumPy array and find the indices of all passengers whose Fare is greater than the overall average Fare. Use those indices to display their Name and Fare.

fare = df['Fare'].to_numpy()

average = np.mean(fare)

ind = np.where(fare > average)[0]

result = df.loc[ind, ['Name', 'Fare']]

print(result)

                                                  Name      Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   53.1000
6                              McCarthy, Mr. Timothy J   51.8625
23                        Sloper, Mr. William Thompson   35.5000
27                      Fortune, Mr. Charles Alexander  263.0000
..                                                 ...       ...
856         Wick, Mrs. George Dennick (Mary Hitchcock)  164.8667
863                  Sage, Miss. Dorothy Edith "Dolly"   69.5500
867               Roebling, Mr. Washington Augustus II   50.4958
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   52.5542
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   83.1583

[211 rows x 2 columns]

In [36]:
#6 
"""
Using Pandas, create a new column FarePerFamilyMember: 
Fare / FamilySize 

Handle any possible division-by-zero issue appropriately. Display the 10 passengers 
with the highest FarePerFamilyMember. 
"""

df['FarePerFamilyMember'] = df['Fare'] / df['FamilySize']

sort = df.sort_values('FarePerFamilyMember', ascending=False)

print(sort[['Name', 'FamilySize', 'Fare', 'FarePerFamilyMember']].head(10))

                                   Name  FamilySize      Fare  \
737              Lesurer, Mr. Gustave J           1  512.3292
258                    Ward, Miss. Anna           1  512.3292
679  Cardeza, Mr. Thomas Drake Martinez           2  512.3292
716       Endres, Miss. Caroline Louise           1  227.5250
380               Bidois, Miss. Rosalie           1  227.5250
557                 Robbins, Mr. Victor           1  227.5250
527                  Farthing, Mr. John           1  221.7792
730       Allen, Miss. Elisabeth Walton           1  211.3375
609           Shutes, Miss. Elizabeth W           1  153.4625
708                Cleaver, Miss. Alice           1  151.5500

     FarePerFamilyMember
737             512.3292
258             512.3292
679             256.1646
716             227.5250
380             227.5250
557             227.5250
527             221.7792
730             211.3375
609             153.4625
708             151.5500

In [42]:
#7 
"""
Create a NumPy feature matrix containing: 
Pclass, Age, SibSp, Parch, Fare, FamilySize 

Replace missing Age values with the median Age, then display: 
 matrix shape  
 first 5 rows  
"""

pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()
familysize = df['FamilySize'].to_numpy()

median = np.nanmedian(age)

age = np.where(np.isnan(age),median,age)

mat = np.column_stack((pclass,age,sibsp,parch,fare,familysize))

print(mat.shape)

print(mat[:5])

(891, 6)
[[ 3.     22.      1.      0.      7.25    2.    ]
 [ 1.     38.      1.      0.     71.2833  2.    ]
 [ 3.     26.      0.      0.      7.925   1.    ]
 [ 1.     35.      1.      0.     53.1     2.    ]
 [ 3.     35.      0.      0.      8.05    1.    ]]

In [ ]:
#8 
"""
Using Pandas groupby() and agg(), calculate for each Pclass: 
 minimum Fare  
 maximum Fare  
 average Fare  
 median Age  
"""

grp = df.groupby('Pclass').agg(
    MinFare=('Fare', 'min'),
    MaxFare=('Fare', 'max'),
    AverageFare=('Fare', 'mean'),
    MedianAge=('Age', 'median')
)

print(grp)

        MinFare   MaxFare  AverageFare  MedianAge
Pclass
1           0.0  512.3292    84.154687       37.0
2           0.0   73.5000    20.662183       29.0
3           0.0   69.5500    13.675550       24.0

In [52]:
#9 
"""
Using NumPy, standardize the Fare column: 
z = (x - mean) / standard deviation 

Create a new DataFrame column called Fare_ZScore, then display the 5 passengers 
with the highest absolute z-score.
"""

df['Fare_ZScore'] = ((df['Fare'] - df['Fare'].mean()) / df['Fare'].std())

result = df.loc[
    df['Fare_ZScore'].abs().sort_values(ascending=False).head(5).index,
    ['Name', 'Age', 'Fare_ZScore']
]

print(result)

                                   Name   Age  Fare_ZScore
258                    Ward, Miss. Anna  35.0     9.661740
679  Cardeza, Mr. Thomas Drake Martinez  36.0     9.661740
737              Lesurer, Mr. Gustave J  35.0     9.661740
341      Fortune, Miss. Alice Elizabeth  24.0     4.644393
27       Fortune, Mr. Charles Alexander  19.0     4.644393

In [60]:
#10 
"""
Create a final feature matrix containing: 
Survived, Pclass, Age, SibSp, Parch, Fare, FamilySize 

Then: 
 Replace missing Age with the median Age.  
 Create FamilySize.  
 Min-max normalize Fare.  
 Convert the final DataFrame to a NumPy matrix.  
 Transpose the matrix.  
 Print the final matrix shape.
"""

survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()
familysize = df['FamilySize'].to_numpy()

age = np.where(np.isnan(age), np.nanmedian(age), age)

fare = (fare - np.min(fare)) / (np.max(fare) - np.min(fare))

mat = np.column_stack((survived, pclass, age, sibsp, parch, fare, familysize))

final = mat.T

print(final.shape)

(7, 891)